services:
  app:
    image: wahab91/portfolio-generator
    container_name: portfolio-pipeline-app
    ports:
      - "8081:80"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb+srv://wowcoupleteam:Wow_3000@cluster0.tonck.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=portfolio320
