version: '3.8'

services:
  app:
    image: wahab91/portfolio-generator
    ports:
      - "80:3000"
    environment:
      - MONGO_URI=mongodb+srv://wowcoupleteam:Wow_3000@cluster0.tonck.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=portfolio320
